image: node:lts

pipelines:

  branches:
    master:
      - step:
          name: Deploy New Version
          deployment: prod
          caches:
            - node
          script:
            - export TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
            # - npm install -g npm-cli-login
            # - npm-cli-login
            - npm version $TAG_VERSION
            - npm publish
